//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;


namespace Webmaster442.Applib.Shaders
{

    /// <summary>
    /// GrayscaleEffect
    /// </summary>
    public class GrayscaleEffect : ShaderEffect
    {
        /// <summary>Dependency property for Input</summary>
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(GrayscaleEffect), 0);

        /// <summary>
        /// Creates a new instance of Grayscale effect
        /// </summary>
        public GrayscaleEffect()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("pack://application:,,,/Webmaster442.Applib2.Wpf;component/Resources/GrayscaleEffect.ps");
            this.PixelShader = pixelShader;

            this.UpdateShaderValue(InputProperty);
        }

        /// <summary>
        /// Input Visual
        /// </summary>
        public Brush Input
        {
            get
            {
                return ((Brush)(this.GetValue(InputProperty)));
            }
            set
            {
                this.SetValue(InputProperty, value);
            }
        }
    }
}
