//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace Webmaster442.Applib.Shaders
{

    /// <summary>
    /// Sepia Pixel shader 2.0 effect
    /// </summary>
    public class SepiaEffect : ShaderEffect
    {
        /// <summary>Dependency property for Input</summary>
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(SepiaEffect), 0);

        /// <summary>
        /// Creates a new instance of Sepia effect
        /// </summary>
        public SepiaEffect()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("pack://application:,,,/Webmaster442.Applib2.Wpf;component/Resources/SepiaEffect.ps");
            this.PixelShader = pixelShader;
            this.UpdateShaderValue(InputProperty);
        }

        /// <summary>
        /// Input Visual
        /// </summary>
        public Brush Input
        {
            get
            {
                return ((Brush)(this.GetValue(InputProperty)));
            }
            set
            {
                this.SetValue(InputProperty, value);
            }
        }
    }
}
