//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace AppLib.WPF.Shaders
{
    /// <summary>
    /// Hue Shift Effect
    /// </summary>
    public class HueShiftEffect : ShaderEffect
    {
        /// <summary>Dependency property for Input</summary>
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(HueShiftEffect), 0);
        /// <summary>Dependency property for HueShift</summary>
        public static readonly DependencyProperty HueShiftProperty = DependencyProperty.Register("HueShift", typeof(double), typeof(HueShiftEffect), new UIPropertyMetadata(((double)(0D)), PixelShaderConstantCallback(0)));

        /// <summary>
        /// Creates a new Instance of HueShiftEffect
        /// </summary>
        public HueShiftEffect()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("pack://application:,,,/AppLib.WPF;component/Resources/HueShiftEffect.ps");
            this.PixelShader = pixelShader;

            this.UpdateShaderValue(InputProperty);
            this.UpdateShaderValue(HueShiftProperty);
        }

        /// <summary>
        /// Input Visual
        /// </summary>
        public Brush Input
        {
            get
            {
                return ((Brush)(this.GetValue(InputProperty)));
            }
            set
            {
                this.SetValue(InputProperty, value);
            }
        }

        /// <summary>Hue shift</summary>
        public double HueShift
        {
            get
            {
                return ((double)(this.GetValue(HueShiftProperty)));
            }
            set
            {
                this.SetValue(HueShiftProperty, value);
            }
        }
    }
}
